import cartImg from '@/assets/mathRog.jpg';

export const products = [
  {
    id: 1,
    promotion: true,
    image: cartImg,
    code: 1040267,
    title: '1Материнська плата Asus PRIME Z790-P',
    price: 3499,
    sale: 200,
    bonus: 13,
    property: {
      proc: 'Intel',
      frequency: '10000',
      memory: '16',
      type: 'am',
    },
  },
  {
    id: 2,
    promotion: true,
    image: cartImg,
    code: 3240672,
    title: '2Материнська плата Asus PRIME Z790-P',
    price: 3499,
    sale: 200,
    bonus: 13,
    property: {
      proc: 'Intel',
      frequency: '10000',
      memory: '16',
      type: 'am',
    },
  },
  {
    id: 3,
    promotion: true,
    image: cartImg,
    code: 3314067,
    title: '3Материнська плата Asus PRIME Z790-P',
    price: 3499,
    sale: 200,
    bonus: 13,
    property: {
      proc: 'Intel',
      frequency: '10000',
      memory: '16',
      type: 'am',
    },
  },
  {
    id: 4,
    promotion: false,
    image: cartImg,
    code: 3040267,
    title: '4Материнська плата Asus PRIME Z790-P',
    price: 3499,
    sale: 200,
    bonus: 13,
    property: {
      proc: 'Intel',
      frequency: '10000',
      memory: '16',
      type: 'am',
    },
  },
  {
    id: 5,
    promotion: false,
    image: cartImg,
    code: 3244067,
    title: '5Материнська плата Asus PRIME Z790-P',
    price: 3499,
    sale: 200,
    bonus: 13,
    property: {
      proc: 'Intel',
      frequency: '10000',
      memory: '16',
      type: 'am',
    },
  },
  {
    id: 6,
    promotion: false,
    image: cartImg,
    code: 3540657,
    title: '6Материнська плата Asus PRIME Z790-P',
    price: 3499,
    sale: 200,
    bonus: 13,
    property: {
      proc: 'Intel',
      frequency: '10000',
      memory: '16',
      type: 'am',
    },
  },
  {
    id: 7,
    promotion: false,
    image: cartImg,
    code: 3046067,
    title: '7Материнська плата Asus PRIME Z790-P',
    price: 3499,
    sale: 200,
    bonus: 13,
    property: {
      proc: 'Intel',
      frequency: '10000',
      memory: '16',
      type: 'am',
    },
  },
];
